// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/DigitalInput.h"
#include "rev/CANSparkMax.h"
#include <frc/DoubleSolenoid.h>
#include <frc/PneumaticsModuleType.h>
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Climber: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
rev::CANSparkMax leaderMotor{10, rev::CANSparkMax::MotorType::kBrushless};
rev::CANSparkMax followerMotor{9, rev::CANSparkMax::MotorType::kBrushless};
frc::DoubleSolenoid heightSolenoid{0, frc::PneumaticsModuleType::CTREPCM, 1, 0};
frc::DoubleSolenoid reachSolenoid{6, frc::PneumaticsModuleType::CTREPCM, 7, 0};
frc::DoubleSolenoid lockSolenoid{4, frc::PneumaticsModuleType::CTREPCM, 5, 0};
std::shared_ptr<frc::DigitalInput> calibrateLimit;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
Climber();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

