// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/Phoenix.h"
#include "frc/DigitalInput.h"
#include "rev/CANSparkMax.h"
#include "frc/motorcontrol/PWMVictorSPX.h"
#include "frc/pidwrappers/PIDMotorController.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class Magazine: public frc::Subsystem {
private:
	int indexStage=0;
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

//rev::CANSparkMax indexerMotor{8, rev::CANSparkMax::MotorType::kBrushless};
std::shared_ptr<frc::DigitalInput> lowSensor;
std::shared_ptr<frc::DigitalInput> highSensor;
frc::PWMVictorSPX hopperMotorTemp = frc::PWMVictorSPX{0};

std::shared_ptr<frc::PIDMotorController> hopperMotor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
Magazine();
	void InitDefaultCommand() override;
	void Periodic() override;
	void SetHopperPower(double power);
	void SetIndexerPower(double power);

	// Return false while detecting ball
	bool GetLowSensor(); 
	bool GetHighSensor();

	void ResetIndexerMotorPosition();
	double GetIndexerMotorPosition();
	void SetIndexerMotorPosition(double position);

	bool Index();
	void CheckNumberOfBallOut();

	void SetIsDeployed(bool setDeployStatus);
	bool GetIsDeployed();

	void SetIsShooting(bool setShootingStatus);

	enum {
		WAITINGFIRSTBALL,
		INDEXFIRSTBALL,
		ENSUREFIRSTBALLPOSITION,
		WAITINGANDINDEXBOTHBALLS,
		INDEXCOMPLETE
	};

	
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


};

