// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutoAim.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Climb.h"
#include "Commands/Drive.h"
#include "Commands/HighGear.h"
#include "Commands/IntakeDeploy.h"
#include "Commands/IntakeRetract.h"
#include "Commands/LowGear.h"
#include "Commands/ShootHigh.h"
#include "Commands/ShootLow.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
operatorGamepad.reset(new frc::Joystick(1));

driverGamepad.reset(new frc::Joystick(0));

driver_Btn1_X.reset(new frc::JoystickButton(driverGamepad.get(), 1));
driver_Btn1_X->WhileHeld(new Climb());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("ShootLow", new ShootLow());
    frc::SmartDashboard::PutData("ShootHigh", new ShootHigh());
    frc::SmartDashboard::PutData("IntakeRetract", new IntakeRetract());
    frc::SmartDashboard::PutData("IntakeDeploy", new IntakeDeploy());
    frc::SmartDashboard::PutData("LowGear", new LowGear());
    frc::SmartDashboard::PutData("HighGear", new HighGear());
    frc::SmartDashboard::PutData("Climb", new Climb());
    frc::SmartDashboard::PutData("AutoAim", new AutoAim());
    frc::SmartDashboard::PutData("Drive", new Drive());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriverGamepad() {
   return driverGamepad;
}

std::shared_ptr<frc::Joystick> OI::getOperatorGamepad() {
   return operatorGamepad;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
