// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/AutoAim.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoAim::AutoAim(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
bool doneAutoAim = false;
int isAimedCnt = 0;
void AutoAim::Initialize() {
    Robot::driveTrain->setLimeLED(true);
}

// Called repeatedly when this Command is scheduled to run
void AutoAim::Execute() {
    if (Robot::driveTrain->autoAim(2) < 1) {
        isAimedCnt++;
    }
    if (isAimedCnt > 50) {
        doneAutoAim = true;
    }
}

// Make this return true when this Command no longer needs to run execute()
bool AutoAim::IsFinished() {
    return doneAutoAim;
}

// Called once after isFinished returns true
void AutoAim::End() {
    isAimedCnt = 0;
    doneAutoAim = false;
    Robot::driveTrain->setLimeLED(false);
    Robot::driveTrain->SetLeftPower(0);
    Robot::driveTrain->SetRightPower(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoAim::Interrupted() {
    End();
}
