// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/RemoveWrongBall.h"
#include <frc/SmartDashboard/SmartDashboard.h>
#include <frc/Timer.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

RemoveWrongBall::RemoveWrongBall(): frc::Command() {
    // Use Requires() here to declare subsystem dependencies
    // eg. Requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void RemoveWrongBall::Initialize() {
    Robot::intake->SetIsShooting(true);
}

// Called repeatedly when this Command is scheduled to run
void RemoveWrongBall::Execute() {
   Robot::intake->SetHopperPower(0.7);
   Robot::intake->SetIndexerPower(-0.3);
   Robot::shooter->SetShooterVelocity(1000, 150);
}

// Make this return true when this Command no longer needs to run execute()
bool RemoveWrongBall::IsFinished() {

    return false;
}

// Called once after isFinished returns true
void RemoveWrongBall::End() {

    Robot::shooter->StopShooterMotor();
    Robot::intake->SetIsShooting(false);


    if (Robot::intake->GetIsDeployed() == true){
        Robot::intake->SetPusherPower(0.8);
        Robot::intake->SetRollerPower(0.8);
        Robot::intake->SetHopperPower(0.6);
    }else{
        Robot::intake->SetHopperPower(0);
        Robot::intake->SetIndexerPower(0);
        Robot::intake->SetRollerPower(0);
        Robot::intake->SetPusherPower(0);
    }
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RemoveWrongBall::Interrupted() {
    End();
}
